version: '2.4'
services:
  challenge:
    build: .
    entrypoint: ["/bin/true"]
  front:
    extends:
      file: ../_docker_manager/docker-compose.yml
      service: front
    depends_on:
      - challenge
  web:
    extends:
      file: ../_web_terminal/docker-compose.yml
      service: web
